### ISSUE TITLE
Problème avec importation de ravenpy

### ISSUE THREAD

**Issue by richardarsenault** [hydrologie/xhydro#56]
### Generic Issue

Avec le setup actuel (xhydro 0.3.0, git clone master puis "pip install -e ."), on a pydantic 2.5.2 qui s'installe avec xarray 2023.10.1.

Cependant, ravenpy a besoin du package pydantic<2.0, >=1.10.8. et de xarray<2023.9.9, >=2022.12.0.

Quand j'essaie d'installer ravenpy, import ravenpy retourne juste un paquet d'erreurs de pydantic et d'erreurs de TypeError @validator, cannot be applied to fields with a schema of str.

Si on peut s'arranger pour avoir une certaine continuité, on pourra mieux gérer ces packages. Je ne sais pas comment régler ce genre de problème alors je m'en remets aux experts!

**Comment by Zeitsperre** [comment]
@richardarsenault

There are issues with the latest `xclim` that forced us to pin xarray in order to maintain support for Python3.8. We'll be listing that pin and dropping that support in v0.48.0.

For `pydantic` the changes are more complex. @huard will be occupying the migration effort from `v1` to `v2` in `ravenpy`.

I don't think there's much we could have done to prevent this. The dependency matrix in `RavenPy` is several years older than `xhydro`. We can start performing integration tests once these two libraries are made compatible.

**Comment by richardarsenault** [comment]
Perfectly understandable, thanks!

I will postpone efforts in deploying ravenpy in xhydro and focus on other features in the meantime. I just wanted to make sure there wasn't anything else I could have done to fix the problem quickly, but if it's more structural/fundamental, I will wait for the versioning to be ironed out. 

Thanks again!

**Comment by richardarsenault** [comment]
Résolu avec le plus récent update de ravenpy.
